name: CI for ASP.NET Core MVC with NUnit and Testmo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore MyMvcCoreApp.sln  # Specify the solution file

    - name: Build the project
      run: dotnet build MyMvcCoreApp.sln --no-restore  # Specify the solution file

    - name: Run tests
      run: dotnet test MyMvcCoreApp.sln --no-build --logger "trx;LogFileName=test-results.trx"  # Specify the solution file
      continue-on-error: true

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: '**/test-results.trx'

    - name: Install Testmo CLI
      run: |
        curl -LO https://testmo.com/cli/testmo-cli-linux.zip  # Ensure correct download URL
        unzip testmo-cli-linux.zip
        sudo mv testmo /usr/local/bin/testmo  # Move Testmo CLI to a directory in the PATH
        sudo chmod +x /usr/local/bin/testmo  # Ensure Testmo CLI is executable

    - name: Upload test results to Testmo
      run: /usr/local/bin/testmo exec --nunit --config testmo.yml -- nunit3-console.exe MyMvcCoreApp.Tests.dll
      env:
        TESTMO_API_KEY: ${{ secrets.TESTMO_API_KEY }}
