name: CI for ASP.NET Core MVC with NUnit and Testmo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore ecommerce/ecommerce.sln

    - name: Build the project
      run: dotnet build ecommerce/ecommerce.sln --no-restore

    - name: Run tests
      run: dotnet test ecommerce/ecommerce.sln --no-build --logger "trx;LogFileName=test-results.trx"
      continue-on-error: true

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: '**/test-results.trx'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  

    - name: Install Testmo CLI
      run: npm install -g @testmo/testmo-cli

    - name: Upload test results to Testmo
      run: testmo import --config testmo.yml --file test-results.trx --type nunit --verbose
      env:
        TESTMO_API_KEY: ${{ secrets.TESTMO_API_KEY }}

    - name: Fallback: Use cURL to upload results (if Testmo CLI fails)
      if: failure()
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.TESTMO_API_KEY }}" \
             -F "file=@test-results.trx" \
             -F "type=nunit" \
             https://your-testmo-instance/api/v1/import/nunit