name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
  
    - name: Install Testmo CLI
      run: npm install -g @testmo/testmo-cli

    - name: Verify Testmo CLI installation
      run: testmo --version

    - name: Restore dependencies
      run: dotnet restore ecommerce/ecommerce.sln

    - name: Build
      run: dotnet build ecommerce/ecommerce.sln --no-restore
    
    - name: Run tests and generate test_results.trx
      run: |
        mkdir -p testing-nunit/TestResults
        dotnet test ecommerce/ecommerce.sln --no-build --verbosity normal --logger "trx;LogFileName=testing-nunit/TestResults/test_results.trx"

    - name: Output directory structure for diagnosis
      run: Get-ChildItem -Recurse -Force

    - name: List test results directory (if exists)
      run: dir testing-nunit\TestResults || echo "TestResults directory not found."

    - name: Upload test results (if file exists)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: TestResults
        path: 'testing-nunit/TestResults/test_results.trx'

    - name: Set Testmo Access Key
      run: echo "TESTMO_ACCESS_KEY=${{ secrets.TESTMO_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Report test results to Testmo (if file exists)
      run: |
        if (Test-Path -Path "testing-nunit/TestResults/test_results.trx") {
          testmo automation:run:submit \
          --instance https://ecommerce-app.testmo.net \
          --project-id 2 \
          --name "Automated Test Run" \
          --source "GitHub" \
          --results trx:testing-nunit/TestResults/test_results.trx
        } else {
          echo "Test results not found. Skipping Testmo submission."
        }
