name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ecommerce/ecommerce.sln

    - name: Build the solution
      run: dotnet build ecommerce/ecommerce.sln --no-restore --configuration Release

    - name: Run NUnit Tests
      run: dotnet test ecommerce/ecommerce.sln --logger "nunit;LogFilePath=TestResults.xml"

    - name: Upload Test Results to Testmo
      env:
        TESTMO_API_KEY: ${{ secrets.TESTMO_API_KEY }}
        TESTMO_PROJECT_ID: ${{ secrets.TESTMO_PROJECT_ID }}
      run: |
        curl -X POST "https://ecommerce-app.testmo.net/api/v1/import/junit" \
        -H "Content-Type: multipart/form-data" \
        -H "Authorization: Bearer $TESTMO_API_KEY" \
        -F "file=@TestResults.xml" \
        -F "project_id=$TESTMO_PROJECT_ID"
