name: Testmo NUnit Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ecommerce/ecommerce.sln

      - name: Build
        run: dotnet build ecommerce/ecommerce.sln --no-restore

      - name: Create results directory
        run: mkdir -p ecommerce/ecommerce/ecommerce/TestResults
