name: Testmo NUnit Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test_results.trx"

      - name: Upload Test Results to Testmo
        run: |
          curl -X POST "https://your-testmo-instance.com/api/v1/import/nunit"
               -H "Authorization: Bearer ${{ secrets.TESTMO_API_KEY }}"
               -F "results=@test_results.trx"
        shell: cmd
