name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
  
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Testmo CLI
      run: npm install -g @testmo/testmo-cli

    - name: Restore dependencies
      run: dotnet restore ecommerce/ecommerce.sln

    - name: Build solution
      run: dotnet build ecommerce/ecommerce.sln --no-restore

    - name: Install NUnit Console Runner
      run: dotnet tool install --global nunit.consolerunner

    - name: Run NUnit tests and generate JUnit XML file
      run: |
        mkdir -p ecommerce/testing-nunit/results
        nunit3-console.exe "ecommerce/testing-nunit/bin/Debug/net8.0/testing-nunit.dll" --result="ecommerce/testing-nunit/results/test-results.xml;transform=nunit3-junit.xslt"
      
    - name: Set Testmo Access Key
      run: echo "TESTMO_ACCESS_KEY=${{ secrets.TESTMO_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: 'ecommerce/testing-nunit/results/test-results.xml'

    - name: Report test results to Testmo
      run: |
        testmo automation:run:submit `
          --instance https://your-instance.testmo.net `
          --project-id 1 `
          --name "NUnit Test Run" `
          --source "unittests" `
          --results ecommerce/testing-nunit/results/test-results.xml
