name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      # Restore your project dependencies
      - name: Restore dependencies
        run: dotnet restore ecommerce.sln

      # Build the ASP.NET Core MVC app
      - name: Build the ecommerce project
        run: dotnet build ecommerce/ecommerce.csproj --no-restore

      # Build the NUnit test project
      - name: Build the ecommerce.nunit project
        run: dotnet build ecommerce.nunit/ecommerce.nunit.csproj --no-restore

      # Run tests and generate NUnit XML results
      - name: Run tests
        run: dotnet test ecommerce.nunit/ecommerce.nunit.csproj --no-build --logger "nunit;LogFileName=results/test-results.xml"
        continue-on-error: true

      # Install Testmo CLI tool locally (then use npx testmo to run it)
      - run: npm install --no-save @testmo/testmo-cli

      # Optionally add a couple of fields such as the git hash and link to the build
      - run: |
          npx testmo automation:resources:add-field --name git --type string \
            --value ${GITHUB_SHA:0:7} --resources resources.json
          RUN_URL="$
